-- 998_reset_all_tables.sql
-- RESET: Drop all tables and start fresh

DROP TABLE IF EXISTS failed_notifications CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS coupons CASCADE;
DROP TABLE IF EXISTS disputes CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS service_tracking CASCADE;
DROP TABLE IF EXISTS service_orders CASCADE;
DROP TABLE IF EXISTS spareparts CASCADE;
DROP TABLE IF EXISTS platform_admins CASCADE;
DROP TABLE IF EXISTS store_admins CASCADE;
DROP TABLE IF EXISTS store_applications CASCADE;
DROP TABLE IF EXISTS stores CASCADE;
DROP TABLE IF EXISTS user_sessions CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Drop custom types (enums)
DROP TYPE IF EXISTS account_status CASCADE;
DROP TYPE IF EXISTS device_type CASCADE;
DROP TYPE IF EXISTS delivery_method CASCADE;
DROP TYPE IF EXISTS order_status CASCADE;
DROP TYPE IF EXISTS payment_status CASCADE;
DROP TYPE IF EXISTS payment_method CASCADE;
DROP TYPE IF EXISTS payment_type CASCADE;
DROP TYPE IF EXISTS payment_record_status CASCADE;
DROP TYPE IF EXISTS sparepart_status CASCADE;
DROP TYPE IF EXISTS order_item_status CASCADE;
DROP TYPE IF EXISTS dispute_type CASCADE;
DROP TYPE IF EXISTS dispute_status CASCADE;
DROP TYPE IF EXISTS created_by_type CASCADE;
DROP TYPE IF EXISTS application_status CASCADE;

-- Drop all functions
DROP FUNCTION IF EXISTS auto_cancel_sla CASCADE;
DROP FUNCTION IF EXISTS reserve_stock CASCADE;
DROP FUNCTION IF EXISTS release_stock CASCADE;
DROP FUNCTION IF EXISTS consume_stock CASCADE;
DROP FUNCTION IF EXISTS swap_sparepart CASCADE;
DROP FUNCTION IF EXISTS update_rating_avg CASCADE;
DROP FUNCTION IF EXISTS get_device_models CASCADE;
DROP FUNCTION IF EXISTS handle_new_user CASCADE;
DROP FUNCTION IF EXISTS rls_auto_enable CASCADE;
DROP FUNCTION IF EXISTS get_home_summary CASCADE;
DROP FUNCTION IF EXISTS get_dashboard_summary CASCADE;
DROP FUNCTION IF EXISTS get_analytics CASCADE;
DROP FUNCTION IF EXISTS generate_order_number CASCADE;
DROP FUNCTION IF EXISTS generate_coupon_code CASCADE;
